spring:
  data:
    redis:
      ttl:
        minutes: 15
      host: localhost
      key:
        prefix:
          drone-key-

    mongodb:
      database: drone
      port: 27017
      host: airguardian-mongodb-1
      password: secret
      username: root
      authentication-database: admin

  kafka:
    bootstrap-servers: http://airguardian-kafka1-1:29092
    properties:
      schema.registry.url: http://airguardian-schema-registry-1:8081

nats:
  url: airguardian-nats-1

air-guardian:
  battery-service:
    battery:
      level:
        for:
          charging: 15.5

