spring:
  data:
    mongodb:
      database: drone
      port: 27017
      host: localhost
      password: secret
      username: root
      authentication-database: admin
  docker:
    compose:
      enabled: true
      file: docker-compose.dev.yml
  kafka:
    bootstrap-servers: localhost:9092
    properties:
      schema.registry.url: http://localhost:8081
nats:
  url: nats://localhost:4222
