spring:
  data:
    mongodb:
      database: drone-test
      port: 27017
      host: localhost
      password: secret
      username: root
      authentication-database: admin
    redis:
      host: localhost
      ttl:
        minutes: 15
      key:
        prefix:
          drone-key-
nats:
  url: nats://localhost:4222
