name: Checks

on:
  push:
    branches: ["main"]
  pull_request:
    branches: '*'

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start MongoDB container
        run: |
          docker run -d --name mongo -p 27017:27017 \
            -e MONGO_INITDB_ROOT_USERNAME=root \
            -e MONGO_INITDB_ROOT_PASSWORD=secret \
            -e MONGO_INITDB_DATABASE=admin \
            mongo:latest

      - name: Start NATS container
        run: docker run -d --name nats -p 4222:4222 nats:latest

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: compile + run all checks
        run: ./gradlew build
